name = "astonnews"
compatibility_date = "2024-09-25"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "aston-news-db"
database_id = "eb9b1371-d272-4c1d-a12a-96cde60e1bdb"
